import os
import subprocess

asm_roman = [
    ('ঁ',   'n'),
    ('ং',   'ng'),
    ('ঃ',   'h'),
    ('অ',   'a'),
    ('আ',   'aa'),
    ('ই',   'i'),
    ('ঈ',   'ii'),
    ('উ',   'u'),
    ('ঋ',   'ra'),
    ('এ',   'e'),
    ('ঐ',   'ai'),
    ('ও',   'o'),
    ('ক',   'ka'),
    ('খ',   'kha'),
    ('গ',   'ga'),
    ('ঘ',   'gha'),
    ('ঙ',   'nga'),
    ('চ',   'cha'),
    ('ছ',   'chha'),
    ('জ',   'ja'),
    ('ঞ',   'nya'),
    ('ট',   'tta'),
    ('ঠ',   'ttha'),
    ('ড',   'dda'),
    ('ঢ',   'ddha'),
    ('ণ',   'nna'),
    ('ত',   'ta'),
    ('থ',   'tha'),
    ('দ',   'da'),
    ('ধ',   'dha'),
    ('ন',   'na'),
    ('প',   'pa'),
    ('ফ',   'pha'),
    ('ব',   'ba'),
    ('ভ',   'bha'),
    ('ম',   'ma'),
    ('য',   'ya'),
    ('র',   'ba'),
    ('ল',   'la'),
    ('শ',   'sha'),
    ('ষ',   'ssa'),
    ('স',   'sa'),
    ('হ',   'ha'),
    ('া',   'aa'),
    ('ি',   'i'),
    ('ী',   'ii'),
    ('ু',   'u'),
    ('ূ',   'uu'),
    ('ৃ',   'ra'),
    ('ে',   'e'),
    ('ৈ',   'ai'),
    ('ো',   'o'),
    ('ৌ',   'au'),
    ('্',   ''),
    ('ৎ',   'ta'),
    ('ৰ',   'ra'),
    ('ৱ',   'ba'),
    ('য়',   'yya'),
    ('০', 'xuinno'),
    ('১', 'ak'),
    ('২', 'dui'),
    ('৩', 'tini'),
    ('৪', 'sari'),
    ('৫', 'pas'),
    ('৬', 'soi'),
    ('৭', 'xat'),
    ('৮', 'ath'),
    ('৯', 'nou'),
    ('।', '  '),
]

def uromanize(input_string, uroman_path):
     for src, dst in asm_roman:
        inputs = input_string.replace(src, dst)
    print (inputs)
    return inputs
